name: Release Zip

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag (e.g., v1.2.3)'
        required: true
      release_notes:
        description: 'Release Notes'
        required: false

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pack Repository
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          ZIP_NAME="kernelsu-${REPO_NAME}.zip"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
          zip -r "$ZIP_NAME" . -x "*.git*" ".github/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          name: ${{ github.event.inputs.release_tag }}
          body: ${{ github.event.inputs.release_notes }}
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
